name: 🐛 Bug Report
description: Nahlásit chybu nebo problém v aplikaci
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Děkujeme za nahlášení bugu! Prosím vyplňte co nejvíce informací.

  - type: textarea
    id: description
    attributes:
      label: Popis problému
      description: Jaký je problém? Co se stalo?
      placeholder: Jasný a stručný popis problému.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Kroky k reprodukci
      description: Jak můžeme problém reprodukovat?
      placeholder: |
        1. Jděte na '...'
        2. Klikněte na '...'
        3. Scrollujte dolů na '...'
        4. Vidíte chybu
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Očekávané chování
      description: Co jste očekávali, že se stane?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Aktuální chování
      description: Co se skutečně stalo?
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Pokud je to relevantní, přidejte screenshots.
      placeholder: Přetáhněte obrázky sem nebo vložte.

  - type: dropdown
    id: browser
    attributes:
      label: Prohlížeč
      description: V jakém prohlížeči k problému dochází?
      multiple: true
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Samsung Internet
        - Jiný
    validations:
      required: true

  - type: input
    id: browser-version
    attributes:
      label: Verze prohlížeče
      placeholder: např. 119.0.6045.105

  - type: dropdown
    id: device
    attributes:
      label: Zařízení
      description: Na jakém zařízení k problému dochází?
      options:
        - Desktop/Laptop
        - Android Smartphone
        - Android Tablet
        - iPhone
        - iPad
        - Jiné
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operační systém
      placeholder: např. Android 13, iOS 17, Windows 11
    validations:
      required: true

  - type: dropdown
    id: pwa
    attributes:
      label: Používáte PWA?
      description: Je aplikace nainstalovaná jako PWA?
      options:
        - "Ano"
        - "Ne"
        - "Nevím"

  - type: textarea
    id: additional
    attributes:
      label: Další kontext
      description: Jakékoliv další informace které by mohly pomoci.
      placeholder: Console errors, network logs, atd.

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: Prohledal jsem existující issues a toto není duplikát
          required: true
        - label: Zkusil jsem problém reprodukovat na nejnovější verzi
          required: true
