name: Bug Bug Report
description: Nahlasit chybu nebo problem v aplikaci
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Dekujeme za nahlaseni bugu! Prosim vyplnte co nejvice informaci.

  - type: textarea
    id: description
    attributes:
      label: Popis problemu
      description: Jaky je problem? Co se stalo?
      placeholder: Jasny a strucny popis problemu.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Kroky k reprodukci
      description: Jak muzeme problem reprodukovat?
      placeholder: |
        1. Jdete na '...'
        2. Kliknete na '...'
        3. Scrollujte dolu na '...'
        4. Vidite chybu
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Ocekavane chovani
      description: Co jste ocekavali, ze se stane?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Aktualni chovani
      description: Co se skutecne stalo?
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Pokud je to relevantni, pridejte screenshots.
      placeholder: Pretahnete obrazky sem nebo vlozte.

  - type: dropdown
    id: browser
    attributes:
      label: Prohlizec
      description: V jakem prohlizeci k problemu dochazi?
      multiple: true
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Samsung Internet
        - Jiny
    validations:
      required: true

  - type: input
    id: browser-version
    attributes:
      label: Verze prohlizece
      placeholder: napr. 119.0.6045.105

  - type: dropdown
    id: device
    attributes:
      label: Zarizeni
      description: Na jakem zarizeni k problemu dochazi?
      options:
        - Desktop/Laptop
        - Android Smartphone
        - Android Tablet
        - iPhone
        - iPad
        - Jine
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operacni system
      placeholder: napr. Android 13, iOS 17, Windows 11
    validations:
      required: true

  - type: dropdown
    id: pwa
    attributes:
      label: Pouzivate PWA?
      description: Je aplikace nainstalovana jako PWA?
      options:
        - "Ano"
        - "Ne"
        - "Nevim"

  - type: textarea
    id: additional
    attributes:
      label: Dalsi kontext
      description: Jakekoliv dalsi informace ktere by mohly pomoci.
      placeholder: Console errors, network logs, atd.

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: Prohledal jsem existujici issues a toto neni duplikat
          required: true
        - label: Zkusil jsem problem reprodukovat na nejnovejsi verzi
          required: true
