name: * Feature Request
description: Navrhnout novou funkci nebo vylepseni
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Dekujeme za vas navrh! Prosim popiste co byste chteli videt v aplikaci.

  - type: textarea
    id: problem
    attributes:
      label: Problem ktery feature resi
      description: Je vas feature request spojeny s problemem? Popiste ho.
      placeholder: Jsem frustrovany kdyz... / Neexistuje zpusob jak...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Navrhovane reseni
      description: Jasny a strucny popis toho, co byste chteli implementovat.
      placeholder: Chtel bych aby aplikace...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternativni reseni
      description: Zvazovali jste nejaka alternativni reseni nebo funkce?
      placeholder: Alternativne by se mohlo...

  - type: dropdown
    id: category
    attributes:
      label: Kategorie
      description: Do ktere kategorie feature patri?
      options:
        - UI/UX vylepseni
        - Nova funkce - Ovladani svetel
        - Nova funkce - Efekty
        - Nova funkce - Sceny
        - Nova funkce - Motory
        - Nova funkce - Pripojeni
        - Performance optimalizace
        - Accessibility
        - Dokumentace
        - Jine
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priorita (vase nazor)
      description: Jak dulezita je pro vas tato funkce?
      options:
        - Nizka - Nice to have
        - Stredni - Bylo by to uzitecne
        - Vysoka - Velmi potrebne
        - Kriticka - Bez toho nelze pracovat
    validations:
      required: true

  - type: textarea
    id: usecase
    attributes:
      label: Use case
      description: Jak byste tuto funkci pouzivali? Konkretni priklad.
      placeholder: |
        Kdyz ovladam show, potrebuji...
        Jako lighting designer pouzivam...
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups / Screenshots
      description: Mate nejake navrhy vzhledu? Pridejte obrazky nebo popiste.
      placeholder: Pretahnete obrazky sem nebo popiste textove.

  - type: textarea
    id: additional
    attributes:
      label: Dalsi kontext
      description: Jakekoliv dalsi informace o feature requestu.
      placeholder: Souvisejici funkce v jinych aplikacich, technicke detaily, atd.

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: Prohledal jsem existujici issues a toto neni duplikat
          required: true
        - label: Cetl jsem dokumentaci a tato funkce tam neni
          required: true
        - label: Jsem ochoten pomoci s implementaci (optional)
          required: false
